"""empty message

Revision ID: 4eaacefea829
Revises: 
Create Date: 2022-02-03 11:09:08.074761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eaacefea829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('imgtype', sa.String(length=4), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_created_at'), 'upload', ['created_at'], unique=False)
    op.create_index(op.f('ix_upload_updated_at'), 'upload', ['updated_at'], unique=False)
    op.create_table('cube',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(length=255), nullable=True),
    sa.Column('back', sa.String(length=255), nullable=True),
    sa.Column('right', sa.String(length=255), nullable=True),
    sa.Column('left', sa.String(length=255), nullable=True),
    sa.Column('top', sa.String(length=255), nullable=True),
    sa.Column('bottom', sa.String(length=255), nullable=True),
    sa.Column('imgtype', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('publish', sa.Boolean(), nullable=False),
    sa.Column('output_img', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['back'], ['upload.img'], ),
    sa.ForeignKeyConstraint(['bottom'], ['upload.img'], ),
    sa.ForeignKeyConstraint(['front'], ['upload.img'], ),
    sa.ForeignKeyConstraint(['left'], ['upload.img'], ),
    sa.ForeignKeyConstraint(['right'], ['upload.img'], ),
    sa.ForeignKeyConstraint(['top'], ['upload.img'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cube_created_at'), 'cube', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cube_created_at'), table_name='cube')
    op.drop_table('cube')
    op.drop_index(op.f('ix_upload_updated_at'), table_name='upload')
    op.drop_index(op.f('ix_upload_created_at'), table_name='upload')
    op.drop_table('upload')
    op.drop_table('roles')
    op.drop_table('users')
    # ### end Alembic commands ###
